### ISSUE TITLE
Periodic reports with the same name require being called with `overwrite = true`

### ISSUE THREAD

**Issue by ChiragKumar9** [CDCgov/ixa#116]
If I try to make two periodic reports with the same name (i.e., the same name but different person properties tabulated in each report), I receive back an error message saying that the report file already exists and I should rerun with `overwrite = true`. If I run with `overwrite = true`, everything completes successfully and the information from each of the two `add_periodic_report` commands (i.e., both person properties that I wanted tabulated) makes its way into the singular report output file.

It's not clear to me what the proper behavior should be for trying to put multiple properties for the same report. I don't necessarily think this is the wrong syntax, but I also don't like having to invoke `overwrite = true` to get two person properties into the same report. If we don't want users to put multiple person properties into the same report, we should put a constraint on that.

Happy to discuss further or make the necessary fixes once we've decided on the best course of action. Thanks.

**Comment by ekr-cfa** [comment]
I think the problem here is actually just the error message, which is kind of misleading. It's just not coherent to try to send two different sets of person properties to the same report file, if only because they will have different columns and so it is not possible to parse the file. In other words, attempting to send two reports to the same file is no different from trying to write a report to a file that already exists, and should return a similar error.

Even ignoring the column issue, however, we would need some real rearchitecture to allow this, given the structure of reports. The reason is that each report is actually a separately opened file from the perspective of Rust, and so trying to write to those files concurrently will have undesirable and unpredictable results, because you are effectively going to be intermixing writes. Depending on how things are configured, you might get a variety of results, including:

- Lines from report A intermixed with report B as expected
- Lines from report A and report B glued together, as in.  `A A B B A` all on one line
- Only lines from report A or report B

This is the same reason why we don't allow reports from multiple threads to the same file.

IOW, I think the fix here is just to tell people they are trying to overwrite but not encourage them to use `overwrite=true`, which will make the problem here worse.

**Comment by ekr-cfa** [comment]
Closing this as WONTFIX.
