### ISSUE TITLE
Unexpected behavior with events not firing on setting of property with default 

### ISSUE THREAD

**Issue by k88hudson-cfa** [CDCgov/ixa#56]
While implementing https://github.com/CDCgov/ixa/pull/47, we noticed some less than ideal behavior with setting properties that have default values. The issue is that because initializers are lazy, if the property is never accessed before a new value is set, an event will not be fired (since no value existed previously). 

For example, say you have a `DiseaseStatus` property that should have a value of `DiseaseStatus::S` by default.

When you call `set_person_property` in order to change the status to `DiseaseStatus::I`, you expect an event to be released; however, because initialization is lazy and the property was never initialized, the event is *not* fired.

```rust
define_person_property_with_default!(DiseaseStatusType, DiseaseStatus, DiseaseStatus::S);

for _ in 0..population_size {
    let person = context.add_person();

    // Infect the person
    context.set_person_property(person, DiseaseStatusType, DiseaseStatus::I);
    
    context.subscribe_to_event(person, |context, event:PersonPropertyChangeEvent<DiseaseStatusType>| {
        // We expect this to fire when set person_property is called
    });
}
```

If instead you call `get_person_property` before setting it, the event *will* be fired.

```rust
define_person_property_with_default!(DiseaseStatusType, DiseaseStatus, DiseaseStatus::S);

for _ in 0..population_size {
    let person = context.add_person();
    // Force initialization
    context.get_person_property(person, DiseaseStatusType);
    // Now the event is fired
    context.set_person_property(person, DiseaseStatusType, DiseaseStatus::I);
    context.subscribe_to_event(person, |context, event:PersonPropertyChangeEvent<DiseaseStatusType>| {
        // We expect this to fire when set person_property is called
    });
}
```

**Comment by ekr-cfa** [comment]
So I think the underlying problem here is that there are two different situations here which use the same API surface:

- I want to set an initial value for a property
- I want to change the value of a property

We want the former to not fire an event but the latter to do so. 

Right now things work like this:

- If there is an initializer then it gets called on `get()` as long as the property is uninitialized and no event fires.
- If you call `set_person_property()`, then it fires an event iff the property is uninitialized

The problem with the second bullet is that sometimes the property is uninitialized because it's lazy and nobody has asked and sometimes it's uninitialized because you're initializing it now (e.g., on person creation). We need some way to distinguish these two.

I can think of a number of approaches:

1.  That each property can only be initialized *either* upfront (with `set_person_property()`) or with an initializer.
2. Create a new API surface with the semantics that it can only be used for initialization and that it never fires an event. E.g.,   (a) a new API called `initialize_person_property()` or (b) something like a builder or macro that bundled up initialization and creation.

(1) is inconvenient operationally, so I favor (2). Specifically, I would create a new function called `initialize_person_property()`. Collectively, these have the following semantics

|  API Call |  Currently None | Currently Some |
|:-------|:-----------------|:-----------------|
| initialize_person_property() | Set value | Panic |
| set_person_property() | Call initializer first if available, then set value and send event, else panic | Set value and send event |

Initializers would have the current semantics.
